language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libpcap-dev

branches:
  only:
  - master

notifications:
  email:
    recipients:
    - bro-commits-internal@bro.org

before_install: pip install --user btest

install: ./configure && make

script: make test BTEST=`which btest`

after_failure: cat testing/diag.log
