language: cpp
compiler:
  - gcc

addons:
  apt:
    packages:
      - python3  # Python 2.7 would also require the ipaddress backport
      - python3-dev
      - libssl-dev

branches:
  only:
  - master

notifications:
  email:
    recipients:
    - bro-commits-internal@bro.org

before_script: ./configure --with-python=`which python3` && make -j4

script: make test
